/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import CEP.buscadorCep;
import Controller.CadastroEquipamentosController;
import Controller.CadastroUsuarioController;
import Controller.UsuarioController;
import Model.CadastroUsuarioModel;
import Model.UsuarioModel;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class TelaRegistroEquipamentos extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistroEquipamentos
     */
    public TelaRegistroEquipamentos() {
        initComponents();
        txtNomeCliente.setEditable(false);
        txtNomeTecnico.setEditable(false);
        txtCliente.setText("00");
        txtTecnico.setText("00");
        txtNomeCliente.setText("Nome não encontrado");
        txtNomeTecnico.setText("Nome não encontrado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        lblTecnico = new javax.swing.JLabel();
        txtTecnico = new javax.swing.JTextField();
        btnPesquisarTecnico = new javax.swing.JButton();
        lblEquipamento = new javax.swing.JLabel();
        txtEquipamento = new javax.swing.JTextField();
        lblDefeito = new javax.swing.JLabel();
        txtDefeito = new javax.swing.JTextField();
        lblServico = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblNomeTecnico = new javax.swing.JLabel();
        txtNomeTecnico = new javax.swing.JTextField();

        setTitle("Registro ordem");
        setResizable(false);

        pnlBase.setLayout(new java.awt.BorderLayout());

        pnlLeft.setPreferredSize(new java.awt.Dimension(50, 278));

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        pnlBase.add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlRight.setPreferredSize(new java.awt.Dimension(50, 278));

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        pnlBase.add(pnlRight, java.awt.BorderLayout.LINE_END);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-manutenção-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de equipamentos");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pnlBase.add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlBottom.setPreferredSize(new java.awt.Dimension(853, 80));

        pnlButtons.setLayout(new java.awt.GridLayout(1, 2));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancelar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSalvar);

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlBase.add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        pnlCenter.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        pnlCenter.setLayout(new java.awt.GridLayout(18, 0, 5, 5));

        lblCliente.setText("ID Cliente:");
        pnlCenter.add(lblCliente);

        txtCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteFocusLost(evt);
            }
        });
        pnlCenter.add(txtCliente);

        btnPesquisarCliente.setText("Pesquisar Cliente");
        btnPesquisarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPesquisarCliente.setPreferredSize(new java.awt.Dimension(60, 23));
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });
        pnlCenter.add(btnPesquisarCliente);

        lblTecnico.setText("Técnico ID:");
        pnlCenter.add(lblTecnico);

        txtTecnico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTecnicoFocusLost(evt);
            }
        });
        pnlCenter.add(txtTecnico);

        btnPesquisarTecnico.setText("Pesquisar Técnico");
        btnPesquisarTecnico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPesquisarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarTecnicoActionPerformed(evt);
            }
        });
        pnlCenter.add(btnPesquisarTecnico);

        lblEquipamento.setText("Equipamento:");
        pnlCenter.add(lblEquipamento);
        pnlCenter.add(txtEquipamento);

        lblDefeito.setText("Defeito:");
        pnlCenter.add(lblDefeito);
        pnlCenter.add(txtDefeito);

        lblServico.setText("Serviço:");
        pnlCenter.add(lblServico);
        pnlCenter.add(txtServico);

        lblValor.setText("Valor:");
        pnlCenter.add(lblValor);
        pnlCenter.add(txtValor);

        lblNomeCliente.setText("Nome Cliente:");
        pnlCenter.add(lblNomeCliente);
        pnlCenter.add(txtNomeCliente);

        lblNomeTecnico.setText("Nome Técnico:");
        pnlCenter.add(lblNomeTecnico);
        pnlCenter.add(txtNomeTecnico);

        pnlBase.add(pnlCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        removeFocusCliente();
        removeFocusTecnico();

        this.dispose();
        TelaOperCadastroEquipamentos tela = new TelaOperCadastroEquipamentos();

        tela.setVisible(true);
        tela.atualizaFechar();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //1. Capturar as informações digitadas pelo usuário
        String cliente = txtCliente.getText();
        String equipamento = txtEquipamento.getText();
        String defeito = txtDefeito.getText();
        String servico = txtServico.getText();
        String tecnico = txtTecnico.getText();
        String valor = txtValor.getText();

        //2. Verificar se não há campos vazios + tratamentos
        if (cliente.isEmpty()) {
            String mensagem = "Cliente não informado!";
            JOptionPane.showMessageDialog(rootPane, mensagem);
            txtCliente.grabFocus();
        } else if (tecnico.isEmpty()) {
            String mensagem = "Técnico não informado";
            JOptionPane.showMessageDialog(rootPane, mensagem);
            txtTecnico.grabFocus();
        } else if (equipamento.isEmpty()) {
            String mensagem = "Equipamento não informado!";
            JOptionPane.showMessageDialog(rootPane, mensagem);
            txtEquipamento.grabFocus();
        } else if (defeito.isEmpty()) {
            String mensagem = "Defeito não informado!";
            JOptionPane.showMessageDialog(rootPane, mensagem);
            txtDefeito.grabFocus();
        } else if (servico.isEmpty()) {
            String mensagem = "Serviço não informado!";
            JOptionPane.showMessageDialog(rootPane, mensagem);
            txtServico.grabFocus();
        } else if (valor.isEmpty()) {
            String mensagem = "Valor não informado";
            JOptionPane.showMessageDialog(rootPane, mensagem);
            txtValor.grabFocus();
        } else {

            String nomeCliente = "";
            CadastroUsuarioController cliente2 = new CadastroUsuarioController();
            CadastroUsuarioModel modelo1 = cliente2.buscarPorIdRegistroCadastroController(txtCliente.getText());
            nomeCliente = modelo1.getNome();

            String nomeTecnico = "";
            UsuarioController tecnico2 = new UsuarioController();
            UsuarioModel modelo2 = tecnico2.buscarPorIdRegistroController(txtTecnico.getText());
            nomeTecnico = modelo2.getUsername();

            if (nomeCliente == null || nomeCliente.isEmpty() || txtCliente.getText() == "") {
                JOptionPane.showMessageDialog(null, "ID inválido ou não existe");

            } else if (nomeTecnico == null || nomeTecnico.isEmpty() || txtTecnico.getText() == "") {
                JOptionPane.showMessageDialog(null, "ID inválido ou não existe");
            } else if (numberOrChar(valor) == false) {
                JOptionPane.showMessageDialog(null, "Verifique números/caracteres");
            } else {

                //3; Enviar os dados para o Controller
                CadastroEquipamentosController op = new CadastroEquipamentosController();
                op.insereEquipamentoCadastroEquipamentosController(equipamento, defeito, servico, tecnico, valor, cliente);

                ////testeAtualizaTabelaAutomatico
                TelaOperCadastroEquipamentos tela = new TelaOperCadastroEquipamentos();

                tela.setVisible(true);
                tela.atualizaFechar();

                this.dispose();

                //3. Criar os dados para o Controller
            }

        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusLost

//        String nomeCliente = "";
//        CadastroUsuarioController cliente = new CadastroUsuarioController();
//        CadastroUsuarioModel modelo = cliente.buscarPorIdRegistroCadastroController(txtCliente.getText());
//        nomeCliente = modelo.getNome();
//        
//        if(nomeCliente == null || nomeCliente.isEmpty() || txtCliente.getText() == ""){
//            txtNomeCliente.setText("Nome não encontrado");
//        }
//        
//        else{
//            txtNomeCliente.setText(nomeCliente);     
//        }

    }//GEN-LAST:event_txtClienteFocusLost

    private void txtTecnicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTecnicoFocusLost

//        String nomeTecnico = "";
//        UsuarioController tecnico = new UsuarioController();
//        UsuarioModel modelo = tecnico.buscarPorIdRegistroController(txtTecnico.getText());
//        nomeTecnico = modelo.getUsername();
//        
//        if(nomeTecnico == null || nomeTecnico.isEmpty() || txtTecnico.getText() == ""){
//            txtNomeTecnico.setText("Nome não encontrado");
//        }
//        
//        else{
//            txtNomeTecnico.setText(nomeTecnico);     
//        }

    }//GEN-LAST:event_txtTecnicoFocusLost

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        String nomeCliente = "";
        CadastroUsuarioController cliente = new CadastroUsuarioController();
        CadastroUsuarioModel modelo = cliente.buscarPorIdRegistroCadastroController(txtCliente.getText());
        nomeCliente = modelo.getNome();

        if (nomeCliente == null || nomeCliente.isEmpty() || txtCliente.getText() == "") {
            txtNomeCliente.setText("Nome não encontrado");
        } else {
            txtNomeCliente.setText(nomeCliente);
        }
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnPesquisarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarTecnicoActionPerformed
        String nomeTecnico = "";
        UsuarioController tecnico = new UsuarioController();
        UsuarioModel modelo = tecnico.buscarPorIdRegistroController(txtTecnico.getText());
        nomeTecnico = modelo.getUsername();

        if (nomeTecnico == null || nomeTecnico.isEmpty() || txtTecnico.getText() == "") {
            txtNomeTecnico.setText("Nome não encontrado");
        } else {
            txtNomeTecnico.setText(nomeTecnico);
        }
    }//GEN-LAST:event_btnPesquisarTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistroEquipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistroEquipamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnPesquisarTecnico;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDefeito;
    private javax.swing.JLabel lblEquipamento;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeTecnico;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDefeito;
    private javax.swing.JTextField txtEquipamento;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeTecnico;
    private javax.swing.JTextField txtServico;
    private javax.swing.JTextField txtTecnico;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public void removeFocusCliente() {

        // Remove focus from button when it gains focus
        txtCliente.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Do nothing to prevent focus change
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Handle lost focus if necessary
            }
        });
    }

    ;
      
      
      
      
         public void removeFocusTecnico() {

        // Remove focus from button when it gains focus
        txtTecnico.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                // Do nothing to prevent focus change
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Handle lost focus if necessary
            }
        });
    }

    ;
         
         
         
         
         public boolean numberOrChar(String number) {
        try {
            Integer.parseInt(number);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

}
